document.write( '<!--footer-->\n' );
document.write( '<footer>\n' );
document.write( '    <div class=\"container-fluid bg-primary\">\n' );
document.write( '        <div class=\"container footer_container\">\n' );
document.write( '            <div class=\"row justify-content-center\">\n' );
document.write( '                <div class=\"col-md-5 d-flex align-items-center \">\n' );
document.write( '                    <img src=\"img/logo-light.svg\" alt=\"sweetaste\" style=\"width:40px;height:40px;\">\n' );
document.write( '                    <p class=\"fs-4 fw-bold mb-0 ps-3 text-white\">訂閱你我的甜蜜郵件</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"col-md-5 py-4\">\n' );
document.write( '                    <form action=\"#\" class=\"d-flex\">\n' );
document.write( '                        <label for=\"email\"><i class=\"fas fa-envelope text-primary bg-secondary\" style=\"font-size: 24px;\"></i></label>\n' );
document.write( '                        <input type=\"mail\" id=\"email\" class=\"form_input_email border-0 p-0 bg-secondary w-100 rounded-0\">\n' );
document.write( '                        <button class=\"bg-warning footer_form_btn p-0  px-4 border-0\"><i class=\"fas fa-arrow-right text-primary fs-4\"></i></button>\n' );
document.write( '                    </form>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '    <div class=\"container-fluid bg-secondary\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '        <div class=\"row justify-content-center py-9\">\n' );
document.write( '            <div class=\"col-lg-5 d-flex flex-column justify-content-between\">\n' );
document.write( '                <img src=\"img/logotype-lg-dark.svg\" alt=\"Sweetaste\" class=\"logo_size_sm mb-9 mb-lg-0\">\n' );
document.write( '                <div class=\"mb-lg-0\">\n' );
document.write( '                    <p class=\"text-primary fw-bolder\">07-1234-5678</p>\n' );
document.write( '                    <p class=\"text-primary fw-bolder\">sweetaste@email.com</p>\n' );
document.write( '                    <p class=\"text-primary fw-bolder\">800 高雄市新興區幸福路 520 號</p>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"col-lg-5 d-none d-lg-flex justify-content-end\">\n' );
document.write( '                <img src=\"img/sm-今天是個吃甜點的好日子.svg\" alt=\"今天是個吃甜點的好日子\" style=\"width:59.28px;\">\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <div class=\"row justify-content-center\">\n' );
document.write( '                <!--social-link-->\n' );
document.write( '                <div class=\"col-md-5 d-flex align-items-center p-0\">\n' );
document.write( '                    <a href=\"#\" class=\"pe-2\"><i class=\"fas fa-at bg-primary text-secondary rounded\" style=\"font-size: 24px;padding: 2px\"></i></a>\n' );
document.write( '                    <a href=\"#\"><i class=\"fab fa-facebook-square text-primary\" style=\"font-size: 32px;\"></i></a>\n' );
document.write( '                </div>\n' );
document.write( '                <!--copyright-->\n' );
document.write( '                <p class=\"col-md-5 text-primary d-flex justify-content-md-end p-0 pt-4 pt-md-0\">© 2018 Sweetaste* All Rights Reserved</p>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '</footer>' );
