document.write( '<!---top_nav-->\n' );
document.write( '<nav class=\"navbar navbar-expand-md navbar-light bg-white py-3\">\n' );
document.write( '    <div class=\"container\">\n' );
document.write( '        <!---phone_toogle_btn-->\n' );
document.write( '        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '            <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '        </button>\n' );
document.write( '        <!--logo-->\n' );
document.write( '        <a class=\"navbar-brand\" href=\"/pages/index.html\">\n' );
document.write( '            <!--md-logo-->\n' );
document.write( '            <img src=\"/img/logo-all-dark.svg\" alt=\"sweetaste 甜點專賣店\" class=\"d-none d-md-flex logo_size_md\">\n' );
document.write( '            <!--sm-logo-->\n' );
document.write( '            <img src=\"/img/logotype-lg-dark.svg\" alt=\"sweetaste 甜點專賣店\" class=\"d-flex d-md-none logo_size_sm\">\n' );
document.write( '        </a>\n' );
document.write( '        <!---phone_purchase_btn-->\n' );
document.write( '        <a href=\"/pages/cart.html\" class=\"d-block d-md-none\">\n' );
document.write( '            <span><i class=\"fas fa-shopping-cart\"></i></span>\n' );
document.write( '        </a>\n' );
document.write( '        <!---nav_list-->\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n' );
document.write( '        <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0 mt-4 mt-lg-0\">\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link px-4 fw-bold\" aria-current=\"page\" href=\"/pages/index.html\">首頁</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link px-4 fw-bold\" href=\"/pages/product.html\">甜點</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link px-4 fw-bold\" href=\"/pages/login.html\">登入</a>\n' );
document.write( '            </li>\n' );
document.write( '        </ul>\n' );
document.write( '        <!---pc_purchase_btn-->\n' );
document.write( '        <a href=\"/pages/cart.html\" class=\"d-none d-md-block \">\n' );
document.write( '            <span><i class=\"fas fa-shopping-cart px-2\"></i></span>\n' );
document.write( '        </a>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '    </nav>\n' );
